name: Network
on:
  pull_request:
    paths: ["terraform-infra/infra/network/dev/**"]
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["terraform-infra/infra/network/dev/**"]

jobs:
  plan:
    if: github.event_name == 'pull_request'
    uses: bar-private-org/reusable-workflows/.github/workflows/terraform-plan-apply.yml@main
    with: { workdir: terraform-infra/infra/network/dev, apply: false }
    secrets: inherit

  apply:
    if: github.event_name == 'push'
    uses: bar-private-org/reusable-workflows/.github/workflows/terraform-plan-apply.yml@main
    with: { workdir: terraform-infra/infra/network/dev, apply: true }
    secrets: inherit
